 
import "./globals.css";
import { Roboto } from "next/font/google";
const rbt = Roboto({
  weight: ["300","400", "500", "700","900"],
  style: "normal",
  subsets: ["latin"],
  fallback: ["system-ui", "sans-serif"],
  display: "swap",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rbt.className}>{children}</body>
    </html>
  );
}
